---
# Overrides for running in a local development cluster (Ex: Docker Desktop)
### CFGOV OVERRIDES ###
image:
  repository: cfgov_python
  pullPolicy: Never
  tag: local

service:
  port: 8000
  type: LoadBalancer

volumes:
  - name: code
    volume:
      hostPath:
        path: ${PROJECT_DIR}
        type: Directory
    mountPath: /src/consumerfinance.gov
  - name: dev-env
    volume:
      hostPath:
        path: ${PROJECT_DIR}/.env
        type: File
    mountPath: /src/consumerfinance.gov/.env
  - name: extend-env
    volume:
      hostPath:
        path: ${PROJECT_DIR}/extend-environment.sh
        type: File
    mountPath: /src/consumerfinance.gov/extend-environment.sh

importDbPath: "${CFGOV_PROD_DB_LOCATION}"

extraEnvs:
  - name: DJANGO_ADMIN_USERNAME
    value: "${DJANGO_ADMIN_USERNAME}"
  - name: DJANGO_ADMIN_PASSWORD
    value: "${DJANGO_ADMIN_PASSWORD}"

### POSTGRESQL OVERRIDES ###
postgresql:
  enabled: true
  postgresqlPostgresPassword: cfpb  # Admin password, admin user is postgres
  postgresqlPassword: cfpb  # User password
  postgresqlUsername: cfpb  # User username
  postgresqlDatabase: cfgov
  persistence:
    enabled: false
  service:
    type: LoadBalancer

### ELASTICSEARCH OVERRIDES ###
elasticsearch:
  enabled: true

  # Disable persistence for local by default
  persistence:
    enabled: false

  replicas: 1
  minimumMasterNodes: 0
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  # Request smaller persistent volumes, if enabled.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "hostpath"
    resources:
      requests:
        storage: 100M

  service:
    type: LoadBalancer

### KIBANA OVERRIDES ###
kibana:
  enabled: true

  persistence:
    enabled: false

  service:
    type: LoadBalancer
