### POSTGRESQL OVERRIDES ###
postgresql:
  enabled: true
  postgresqlPostgresPassword: cfpb  # Admin password, admin user is postgres
  postgresqlPassword: cfpb  # User password
  postgresqlUsername: cfpb  # User username
  postgresqlDatabase: cfgov
  persistence:
    enabled: false
  service:
    type: LoadBalancer

### OPENSEARCH OVERRIDES ###
opensearch:
  enabled: true

  persistence:
    enabled: false  # Disable persistence for local by default
#    # Request smaller persistent volumes, if enabled.
#    accessModes: [ "ReadWriteOnce" ]
#    storageClass: "hostpath"
#    size: 100M

  replicas: 2

  # antiAffinity: "soft"

  # Shrink default JVM heap.
  # opensearchJavaOpts: "-Xmx512m -Xms512m"
#
#  # Allocate smaller chunks of memory per pod.
#  resources:
#    requests:
#      cpu: "25m"
#      memory: "100M"
#    limits:
#      cpu: "500m"
#      memory: "2048M"

  service:
    type: LoadBalancer

### KIBANA OVERRIDES ###
opensearch-dashboards:
  enabled: true

  persistence:
    enabled: false

  service:
    type: LoadBalancer
