### POSTGRESQL OVERRIDES ###
postgresql:
  enabled: true
  postgresqlPostgresPassword: cfpb  # Admin password, admin user is postgres
  postgresqlPassword: cfpb  # User password
  postgresqlUsername: cfpb  # User username
  postgresqlDatabase: cfgov
  persistence:
    enabled: false
  service:
    type: LoadBalancer

### OPENSEARCH OVERRIDES ###
opensearch:
  enabled: true

  persistence:
    enabled: false  # Disable persistence for local by default
#    # Request smaller persistent volumes, if enabled.
#    accessModes: [ "ReadWriteOnce" ]
#    storageClass: "hostpath"
#    size: 100M

  extraEnvs:
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"

  replicas: 2

  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      # Bind to all interfaces because we don't know what IP address Docker will assign to us.
      network.host: 0.0.0.0
      # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
      # discovery.type: single-node
      # Disable Security
      plugins.security.disabled: true
  # antiAffinity: "soft"

  # Shrink default JVM heap.
  # opensearchJavaOpts: "-Xmx512m -Xms512m"
#
#  # Allocate smaller chunks of memory per pod.
#  resources:
#    requests:
#      cpu: "25m"
#      memory: "100M"
#    limits:
#      cpu: "500m"
#      memory: "2048M"

  service:
    type: LoadBalancer

### KIBANA OVERRIDES ###
kibana:
  enabled: true

  persistence:
    enabled: false

  service:
    type: LoadBalancer
